# Generated by Django 3.2 on 2021-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebank',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
