# Generated by Django 3.2 on 2021-05-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0002_alter_employeebank_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='prescription',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
